### ISSUE TITLE
Incompatible packages 

### ISSUE THREAD

**Issue by YanjunLiu2** [TimoSommer/superconductors_3D#1]
Dear Contributors,

When I tried to create the virtual env following your instructions, I got the following problem:

yanjunliu@Yanjuns-MacBook-Pro 3DSC % conda env create -f ./environment.yaml --name 3DSC1
Channels:
 - arturo.mendoza.quispe
 - conda-forge
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - arturo.mendoza.quispe
 - conda-forge
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested libxcb 1.14**
  - nothing provides requested libstdcxx-ng 9.3.0**
  - nothing provides requested libgomp 9.3.0**
  - nothing provides requested libgfortran-ng 7.5.0**
  - nothing provides requested libgcc-ng 9.3.0**
  - nothing provides requested cudatoolkit 10.2.89**
  - nothing provides requested _openmp_mutex 4.5**
  - package pyqt-5.9.2-py39h23ab428_6 requires python >=3.9,<3.10.0a0, but none of the providers can be installed
  - package scipy-1.6.2-py37h4420a3a_0 requires libgfortran >=3.0.1,<4.0.0.a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ _openmp_mutex 4.5**  does not exist (perhaps a typo or a missing channel);
├─ cudatoolkit 10.2.89**  does not exist (perhaps a typo or a missing channel);
├─ libgcc-ng 9.3.0**  does not exist (perhaps a typo or a missing channel);
├─ libgfortran-ng 7.5.0**  does not exist (perhaps a typo or a missing channel);
├─ libgfortran4 7.5.0**  is installable with the potential options
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 3, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_14, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_15, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_16, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_17, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_18, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_19, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_20, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_21, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_22, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_23, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_10, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_11, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 4, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 5, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 6, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_7, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_8, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_9, which can be installed;
│  ├─ libgfortran4 7.5.0 would require
│  │  └─ libgfortran 4.0.0 *_12, which can be installed;
│  └─ libgfortran4 7.5.0 would require
│     └─ libgfortran 4.0.0 *_13, which can be installed;
├─ libgomp 9.3.0**  does not exist (perhaps a typo or a missing channel);
├─ libstdcxx-ng 9.3.0**  does not exist (perhaps a typo or a missing channel);
├─ libxcb 1.14**  does not exist (perhaps a typo or a missing channel);
├─ libzlib 1.2.11**  is installable with the potential options
│  ├─ libzlib 1.2.11 would require
│  │  └─ zlib 1.2.11 *_1014, which can be installed;
│  ├─ libzlib 1.2.11 would require
│  │  └─ zlib 1.2.11 *_1012, which can be installed;
│  └─ libzlib 1.2.11 would require
│     └─ zlib 1.2.11 *_1013, which can be installed;
├─ mkl 2021.2.0**  is installable with the potential options
│  ├─ mkl 2021.2.0, which can be installed;
│  └─ mkl 2021.2.0 would require
│     └─ tbb 2021.* , which can be installed;
├─ pyqt 5.9.2**  is installable with the potential options
│  ├─ pyqt 5.9.2 would require
│  │  └─ python >=3.9,<3.10.0a0  with the potential options
│  │     ├─ python [3.9.0|3.9.1|3.9.2] would require
│  │     │  └─ python_abi 3.9.* *_cp39, which can be installed;
│  │     ├─ python [3.9.10|3.9.12|3.9.13] would require
│  │     │  ├─ pypy3.9 7.3.8.* , which requires
│  │     │  │  └─ tk >=8.6.12,<8.7.0a0  with the potential options
│  │     │  │     ├─ tk 8.6.12, which can be installed;
│  │     │  │     ├─ tk 8.6.13 would require
│  │     │  │     │  └─ libzlib >=1.2.13,<1.3.0a0  with the potential options
│  │     │  │     │     ├─ libzlib 1.2.13 would require
│  │     │  │     │     │  └─ zlib 1.2.13 *_4, which can be installed;
│  │     │  │     │     └─ libzlib 1.2.13 would require
│  │     │  │     │        └─ zlib 1.2.13 *_5, which can be installed;
│  │     │  │     └─ tk [8.6.11|8.6.12] would require
│  │     │  │        └─ zlib >=1.2.12,<1.3.0a0 , which can be installed;
│  │     │  └─ tk >=8.6.12,<8.7.0a0  with the potential options
│  │     │     ├─ tk 8.6.12, which can be installed;
│  │     │     ├─ tk 8.6.13, which can be installed (as previously explained);
│  │     │     └─ tk [8.6.11|8.6.12], which can be installed (as previously explained);
│  │     ├─ python [3.9.10|3.9.11|3.9.12|3.9.7|3.9.9] would require
│  │     │  └─ tk >=8.6.11,<8.7.0a0  with the potential options
│  │     │     ├─ tk 8.6.11, which can be installed;
│  │     │     ├─ tk 8.6.12, which can be installed;
│  │     │     ├─ tk 8.6.13, which can be installed (as previously explained);
│  │     │     └─ tk [8.6.11|8.6.12], which can be installed (as previously explained);
│  │     ├─ python 3.9.12 would require
│  │     │  └─ pypy3.9 7.3.9.*  with the potential options
│  │     │     ├─ pypy3.9 [7.3.8|7.3.9], which can be installed (as previously explained);
│  │     │     ├─ pypy3.9 7.3.9 would require
│  │     │     │  └─ zlib >=1.2.12,<1.3.0a0 , which can be installed;
│  │     │     ├─ pypy3.9 7.3.9 would require
│  │     │     │  └─ libzlib >=1.2.12,<1.3.0a0  with the potential options
│  │     │     │     ├─ libzlib 1.2.12 would require
│  │     │     │     │  └─ zlib 1.2.12 *_0, which can be installed;
│  │     │     │     ├─ libzlib 1.2.12 would require
│  │     │     │     │  └─ zlib 1.2.12 *_3, which can be installed;
│  │     │     │     ├─ libzlib 1.2.12 would require
│  │     │     │     │  └─ zlib 1.2.12 *_4, which can be installed;
│  │     │     │     ├─ libzlib 1.2.12 would require
│  │     │     │     │  └─ zlib 1.2.12 *_1, which can be installed;
│  │     │     │     ├─ libzlib 1.2.12 would require
│  │     │     │     │  └─ zlib 1.2.12 *_2, which can be installed;
│  │     │     │     ├─ libzlib 1.2.13, which can be installed (as previously explained);
│  │     │     │     └─ libzlib 1.2.13, which can be installed (as previously explained);
│  │     │     └─ pypy3.9 [7.3.11|7.3.12|7.3.13|7.3.15|7.3.9] would require
│  │     │        └─ libzlib >=1.2.13,<1.3.0a0 , which can be installed (as previously explained);
│  │     ├─ python [3.9.4|3.9.5] would require
│  │     │  └─ sqlite >=3.35.5,<4.0a0  with the potential options
│  │     │     ├─ sqlite 3.35.5, which can be installed;
│  │     │     ├─ sqlite [3.36.0|3.37.0|...|3.38.5], which can be installed;
│  │     │     ├─ sqlite [3.38.3|3.38.5|...|3.39.3] would require
│  │     │     │  └─ zlib >=1.2.12,<1.3.0a0 , which can be installed;
│  │     │     ├─ sqlite [3.39.2|3.39.3|3.39.4] would require
│  │     │     │  └─ libzlib >=1.2.12,<1.3.0a0 , which can be installed (as previously explained);
│  │     │     ├─ sqlite [3.40.0|3.41.2|...|3.45.1] would require
│  │     │     │  └─ libzlib >=1.2.13,<1.3.0a0 , which can be installed (as previously explained);
│  │     │     ├─ sqlite [3.40.0|3.40.1] would require
│  │     │     │  └─ zlib >=1.2.13,<1.3.0a0 , which can be installed;
│  │     │     └─ sqlite [3.41.1|3.41.2] would require
│  │     │        └─ zlib >=1.2.13,<2.0a0 , which can be installed;
│  │     ├─ python [3.9.6|3.9.7] would require
│  │     │  └─ sqlite >=3.36.0,<4.0a0  with the potential options
│  │     │     ├─ sqlite [3.36.0|3.37.0|...|3.38.5], which can be installed;
│  │     │     ├─ sqlite [3.38.3|3.38.5|...|3.39.3], which can be installed (as previously explained);
│  │     │     ├─ sqlite [3.39.2|3.39.3|3.39.4], which can be installed (as previously explained);
│  │     │     ├─ sqlite [3.40.0|3.41.2|...|3.45.1], which can be installed (as previously explained);
│  │     │     ├─ sqlite [3.40.0|3.40.1], which can be installed (as previously explained);
│  │     │     └─ sqlite [3.41.1|3.41.2], which can be installed (as previously explained);
│  │     ├─ python [3.9.14|3.9.15|3.9.16|3.9.17|3.9.18] would require
│  │     │  ├─ libzlib >=1.2.13,<1.3.0a0 , which can be installed (as previously explained);
│  │     │  └─ pypy3.9 [7.3.11.* |7.3.12.* |7.3.13.* |7.3.15.* ], which can be installed (as previously explained);
│  │     ├─ python [3.9.0|3.9.1|3.9.2|3.9.4|3.9.5], which can be installed;
│  │     ├─ python [3.9.12|3.9.13] would require
│  │     │  └─ zlib >=1.2.12,<1.3.0a0 , which can be installed;
│  │     └─ python [3.9.15|3.9.16|3.9.17|3.9.18] would require
│  │        └─ zlib >=1.2.13,<1.3.0a0 , which can be installed;
│  └─ pyqt 5.9.2 would require
│     └─ sip >=4.19.4,<=4.19.8 , which can be installed;
├─ python 3.8.6**  is not installable because it conflicts with any installable versions previously reported;
├─ python_abi 3.8**  is installable with the potential options
│  ├─ python_abi 3.8 conflicts with any installable versions previously reported;
│  └─ python_abi 3.8 would require
│     └─ pypy3.8 7.3.*  with the potential options
│        ├─ pypy3.8 [7.3.6|7.3.7] would require
│        │  └─ tk >=8.6.11,<8.7.0a0  with the potential options
│        │     ├─ tk 8.6.11, which can be installed;
│        │     ├─ tk 8.6.12, which can be installed;
│        │     ├─ tk 8.6.13, which can be installed (as previously explained);
│        │     └─ tk [8.6.11|8.6.12], which can be installed (as previously explained);
│        ├─ pypy3.8 [7.3.8|7.3.9] would require
│        │  └─ tk >=8.6.12,<8.7.0a0  with the potential options
│        │     ├─ tk 8.6.12, which can be installed;
│        │     ├─ tk 8.6.13, which can be installed (as previously explained);
│        │     └─ tk [8.6.11|8.6.12], which can be installed (as previously explained);
│        ├─ pypy3.8 7.3.9 would require
│        │  └─ zlib >=1.2.12,<1.3.0a0 , which can be installed;
│        ├─ pypy3.8 7.3.9 would require
│        │  └─ libzlib >=1.2.12,<1.3.0a0 , which can be installed (as previously explained);
│        └─ pypy3.8 [7.3.11|7.3.9] would require
│           └─ libzlib >=1.2.13,<1.3.0a0 , which can be installed (as previously explained);
├─ pyyaml 5.1.2**  is installable with the potential options
│  ├─ pyyaml 5.1.2, which can be installed;
│  ├─ pyyaml 5.1.2 would require
│  │  └─ yaml >=0.1.7,<0.2.0a0 , which can be installed;
│  └─ pyyaml 5.1.2 would require
│     └─ python_abi * *_cp38, which can be installed;
├─ scipy 1.6.2**  is not installable because there are no viable options
│  ├─ scipy 1.6.2 would require
│  │  └─ libgfortran >=3.0.1,<4.0.0.a0 , which conflicts with any installable versions previously reported;
│  ├─ scipy 1.6.2 would require
│  │  └─ libgfortran 5.* , which conflicts with any installable versions previously reported;
│  └─ scipy 1.6.2 would require
│     └─ mkl >=2019.4,<2020.0a0 , which conflicts with any installable versions previously reported;
├─ sip 4.19.13**  is not installable because it conflicts with any installable versions previously reported;
├─ sqlite 3.35.4**  is not installable because it conflicts with any installable versions previously reported;
├─ tbb 2020.3**  is not installable because it conflicts with any installable versions previously reported;
├─ tk 8.6.10**  is not installable because it conflicts with any installable versions previously reported;
├─ yaml 0.2.5**  is not installable because it conflicts with any installable versions previously reported;
└─ zlib 1.2.11**  is not installable because it conflicts with any installable versions previously reported.

Do you know what may cause the problem? I want to use the functions for generating magpie and dsoap features particularly. Thank you very much!

Best regards,

Yanjun

**Comment by TimoSommer** [comment]
Dear Yanjun, the issue might be the channel priority in conda. I remember that I had similar issues until I set conda's channel_priority to false. This is explained in point 3 of the installation instructions. Please give this a try and let me know if it works for you. 
Another issue might be that you're using MacOs. The code was developed with and for Linux, so it might be that there are some issues. The focus of this project was building up the 3DSC database, not writing the best code.
If you're only interested in the magpie features, it would be easier to install the chemml package which contains these features. The pure SOAP features are in the dscribe package. Or do you have disordered crystal structures for which you necessarily need the DSOAP features? In this case I could setup these features in a new github repo.

**Comment by YanjunLiu2** [comment]
Dear Timo,

Thanks for the response! To set conda's channel_priority to false I need to vi ~/.condarc and add a line "channel_priority=false" right? I tried to install chemml but there are also packages dependency issues. It seems that they haven't maintained the package for a while. I'm doing some preliminary ml trials on 3DSC and the original supercon data and my plan is to start with magpie and incorporate structure information step by step. Currently I haven't look into dsoap since obviously I don't even have access to magpie yet lol. But as dsoap is a nice way you guys brought out to describe the disorder materials in supercon I think I may try to use it in the future. Thank you very much!

**Comment by TimoSommer** [comment]
Dear Yanjun, 

yes,  that is how you add the channel priority. Most likely, there already is a line called 'channel_priority' where you have to change the value and save the file. You should redo this after installing the 3DSC conda environment, it is only important during installation of the packages.
If you have any more questions, please let me know!
